### ISSUE TITLE
Cannot watch anime episode including float anime episode

### ISSUE THREAD

**Issue by clouedoc** [saikou-app/saikou#421]
### Summary

I cannot watch a specific episode

### Reproduction Steps

1. Open app
2. Search for anime "that time I was reincarnated as a slime"
3. Select Gogo animé
4. Pick episode 24.5
5. Crash!

### Expected Result

The video plays without crashing

### Actual Result

The first frames of the video play but the player disappears.

### Device Information

Saikou Version: 1.2.0.20
Device: google oriole
Architecture: aarch64
OS Version: REL 13 (33)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

### Additional Information

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221005.002/2022100300:user/release-keys
package: ani.saikou.beta:61
process: ani.saikou.beta

java.lang.NumberFormatException: For input string: "24.5"
	at java.lang.Integer.parseInt(Integer.java:747)
	at java.lang.Integer.parseInt(Integer.java:865)
	at ani.saikou.anime.ExoplayerView$onRenderedFirstFrame$1.invokeSuspend(ExoplayerView.kt:1170)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@685f66a, Dispatchers.IO]

```

**Comment by Adolar0042** [comment]
Works for me, are you on the latest beta?

![image](https://user-images.githubusercontent.com/39769465/195438244-87d9c5d9-6868-4171-a03e-15b25cffd987.png)

**Comment by Adolar0042** [comment]
also, as a side note: you will get the best quality for that time i got reincarnated as a slime with Kamyroll

**Comment by clouedoc** [comment]
Hello Adolar, it indeed works fine with the latest beta.
I will remember to try it before reporting any further bugs.
Thank you for your help, your recommendation, and your work on the app (I believe you did some, since you have a fancy "collaborator" badge 😃 )
I'll close this issue

**Comment by Adolar0042** [comment]
Great to hear everything works!
Have fun watching \(ᵔᵕᵔ)/
