### ISSUE TITLE
Allanime [Source Error]

### ISSUE THREAD

**Issue by gaminglnk** [saikou-app/saikou#671]
### Summary

Unable to play or load episodes of any anime through Allanime.

### Reproduction Steps

Just try playing any episode of any anime through Allanime source.

### Expected Result

This should work fine and the anime episode should at least be visible.

### Actual Result

For an anime [Chainsaw Man,](https://anilist.co/anime/127230)

It's giving the following error :
```
java.lang.Exception: Var : {"search":{"allowAdult":false,"query":"Chainsaw Man"},"translationType":"sub"}
Error : PersistedQueryNotFound
	at ani.saikou.parsers.anime.AllAnime.graphqlQuery(AllAnime.kt:141)
	at ani.saikou.parsers.anime.AllAnime.access$graphqlQuery(AllAnime.kt:15)
	at ani.saikou.parsers.anime.AllAnime$graphqlQuery$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

### Device Information

Saikou Version: 1.2.2.1
Device: motorola rhode
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by brahmkshatriya** [comment]
Update to 1.2.3.0 😐
