### ISSUE TITLE
Saikou sources not loading

### ISSUE THREAD

**Issue by OofMon2301** [saikou-app/saikou#724]
### Summary

Every source currently available has shown either one server (usually YT-HD) or none at all, and giving an "expected url scheme http or https" error shortly afterwards.

### Reproduction Steps

Opening any episode in any anime.

### Expected Result

Should show a vast range of servers and with some having the file size of the episode (for example, YT-SD or YT-HD).

### Actual Result

Shows one (with YT-HD with no file size description) or none at all, giving the error:

```
java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for 404: N...
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1261)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
	at okhttp3.Request$Builder.url(Request.kt:208)
	at dev.brahmkshatriya.nicehttp.RequestsKt.requestCreator(Requests.kt:72)
	at dev.brahmkshatriya.nicehttp.Requests.custom$suspendImpl(Requests.kt:148)
	at dev.brahmkshatriya.nicehttp.Requests.custom(Unknown Source:0)
	at dev.brahmkshatriya.nicehttp.Requests.get(Requests.kt:185)
	at dev.brahmkshatriya.nicehttp.Requests.get$default(Requests.kt:172)
	at ani.saikou.parsers.anime.extractors.StreamSB.extract(StreamSB.kt:18)
	at ani.saikou.parsers.anime.extractors.StreamSB$extract$1.invokeSuspend(Unknown Source:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at ani.saikou.NetworkKt.asyncMap(Network.kt:92)
	at ani.saikou.parsers.AnimeParser$loadByVideoServers$2.invokeSuspend(AnimeParser.kt:80)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### Device Information

Saikou Version 1.2.3.0
Model: Xiaomi 13 Pro
Android Version: 13

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by Nevenon** [comment]
Me two I can't watch anything

**Comment by Shifathosen** [comment]
Same 😤

**Comment by sunoudoumu** [comment]
I've also been dealing with this issue. before it was just gogo, but now it's every single source for every episode of every anime.

**Comment by Nevenon** [comment]
Sunoudoumu. How?

**Comment by sunoudoumu** [comment]
I went to the saikou discord and installed the latest debug build under the status tab.

**Comment by Nevenon** [comment]
> I went to the saikou discord and installed the latest debug build under the status tab.
Thanks it works again

**Comment by sunoudoumu** [comment]
no problem! glad I could help :)
