### ISSUE TITLE
9anime not working.

### ISSUE THREAD

**Issue by Shebyyy** [saikou-app/saikou#765]
### Summary

Whenever I select 9anime it give error.

### Reproduction Steps

.

### Expected Result

.

### Actual Result

The following error appeared:

kotlinx.serialization.MissingFieldException: Field 'url' is required for type with serial name 'ani.saikou.parsers.anime.NineAnime.SearchData', but it was missing at path: $
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:90)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:97)
	at ani.saikou.Mapper.parse(Network.kt:76)
	at ani.saikou.parsers.anime.NineAnime.encodeVrf(NineAnime.kt:189)
	at ani.saikou.parsers.anime.NineAnime.access$encodeVrf(NineAnime.kt:12)
	at ani.saikou.parsers.anime.NineAnime$encodeVrf$1.invokeSuspend(Unknown Source:15)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.serialization.MissingFieldException: Field 'url' is required for type with serial name 'ani.saikou.parsers.anime.NineAnime.SearchData', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at ani.saikou.parsers.anime.NineAnime$SearchData.<init>(NineAnime.kt:144)
	at ani.saikou.parsers.anime.NineAnime$SearchData$$serializer.deserialize(NineAnime.kt:144)
	at ani.saikou.parsers.anime.NineAnime$SearchData$$serializer.deserialize(NineAnime.kt:144)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	... 13 more

### Device Information

Saikou Version: 1.2.5.1405965
Device: vivo 2111
Architecture: aarch64
OS Version: REL 12 (31)

### Checklist

- [X] I have searched the open AND closed issues for any duplicates.

**Comment by DaniD3v** [comment]
this can be closed, doesn't apply anymore

**Comment by Shebyyy** [comment]
Aniwave still not working....

Sometimes it shows 1 server but that 1 also didn't work.
Please check 🙏
